# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stats', '0004_auto_20170621_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedlineup',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='baselineup',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='coachseason',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='coachteamrosterxref',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='fourfactorslineup',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='misclineup',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='opponentlineup',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playeradvancedonoffdetail',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playeradvancedsplit',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playerbaseonoffdetail',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playercontractseason',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playerdefensetracking',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playerefficiencytracking',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playerfourfactorsonoffdetail',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playergamelog',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playermisconoffdetail',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playermiscsplit',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playeronoffsummary',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playeropponentonoffdetail',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playerpassingtracking',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playerpossessionstracking',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playerreboundingtracking',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playerscoringonoffdetail',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playerscoringsplit',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playerseason',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playershootingsplit',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playershottypetracking',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playerspeeddistancetracking',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playerteamrosterxref',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playertouchtracking',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playertraditionalsplit',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='playerusagesplit',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='scoringlineup',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='teamadvancedsplit',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='teamdefensesplit',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='teamfourfactorssplit',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='teammiscsplit',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='teamopponentsplit',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='teamscoringsplit',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='teamshootingsplit',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='teamtraditionalsplit',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AddField(
            model_name='usagelineup',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_stats.LeagueSeason'),
        ),
        migrations.AlterUniqueTogether(
            name='coachseason',
            unique_together=set([('coach', 'team_id', 'season')]),
        ),
        migrations.AlterUniqueTogether(
            name='coachteamrosterxref',
            unique_together=set([('team', 'coach', 'season', 'coach_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='playeradvancedonoffdetail',
            unique_together=set([('season', 'season_type', 'measure_type', 'per_mode', 'team', 'player', 'court_status')]),
        ),
        migrations.AlterUniqueTogether(
            name='playeradvancedsplit',
            unique_together=set([('player', 'season', 'season_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerbaseonoffdetail',
            unique_together=set([('season', 'season_type', 'measure_type', 'per_mode', 'team', 'player', 'court_status')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerdefensetracking',
            unique_together=set([('player', 'season', 'season_type', 'pt_measure_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerefficiencytracking',
            unique_together=set([('player', 'season', 'season_type', 'pt_measure_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerfourfactorsonoffdetail',
            unique_together=set([('season', 'season_type', 'measure_type', 'per_mode', 'team', 'player', 'court_status')]),
        ),
        migrations.AlterUniqueTogether(
            name='playermisconoffdetail',
            unique_together=set([('season', 'season_type', 'measure_type', 'per_mode', 'team', 'player', 'court_status')]),
        ),
        migrations.AlterUniqueTogether(
            name='playermiscsplit',
            unique_together=set([('player', 'season', 'season_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='playeronoffsummary',
            unique_together=set([('season', 'season_type', 'measure_type', 'per_mode', 'team', 'player', 'court_status')]),
        ),
        migrations.AlterUniqueTogether(
            name='playeropponentonoffdetail',
            unique_together=set([('season', 'season_type', 'measure_type', 'per_mode', 'team', 'player', 'court_status')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerpassingtracking',
            unique_together=set([('player', 'season', 'season_type', 'pt_measure_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerpossessionstracking',
            unique_together=set([('player', 'season', 'season_type', 'pt_measure_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerreboundingtracking',
            unique_together=set([('player', 'season', 'season_type', 'pt_measure_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerscoringonoffdetail',
            unique_together=set([('season', 'season_type', 'measure_type', 'per_mode', 'team', 'player', 'court_status')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerscoringsplit',
            unique_together=set([('player', 'season', 'season_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerseason',
            unique_together=set([('player', 'season', 'season_type', 'team', 'per_mode')]),
        ),
        migrations.AlterUniqueTogether(
            name='playershootingsplit',
            unique_together=set([('player', 'season', 'season_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='playershottypetracking',
            unique_together=set([('player', 'season', 'season_type', 'pt_measure_type', 'per_mode', 'group_set', 'group_value', 'shot_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerspeeddistancetracking',
            unique_together=set([('player', 'season', 'season_type', 'pt_measure_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerteamrosterxref',
            unique_together=set([('team', 'player', 'season')]),
        ),
        migrations.AlterUniqueTogether(
            name='playertouchtracking',
            unique_together=set([('player', 'season', 'season_type', 'pt_measure_type', 'per_mode', 'group_set', 'group_value', 'touch_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='playertraditionalsplit',
            unique_together=set([('player', 'season', 'season_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerusagesplit',
            unique_together=set([('player', 'season', 'season_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='teamadvancedsplit',
            unique_together=set([('team', 'season', 'season_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='teamdefensesplit',
            unique_together=set([('team', 'season', 'season_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='teamfourfactorssplit',
            unique_together=set([('team', 'season', 'season_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='teammiscsplit',
            unique_together=set([('team', 'season', 'season_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='teamopponentsplit',
            unique_together=set([('team', 'season', 'season_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='teamscoringsplit',
            unique_together=set([('team', 'season', 'season_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='teamseason',
            unique_together=set([('season', 'season_type', 'team', 'per_mode')]),
        ),
        migrations.AlterUniqueTogether(
            name='teamshootingsplit',
            unique_together=set([('team', 'season', 'season_type', 'per_mode', 'group_set', 'group_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='teamtraditionalsplit',
            unique_together=set([('team', 'season', 'season_type', 'per_mode', 'group_set', 'group_value')]),
        ),
    ]
