# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stats', '0005_auto_20170621_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='season',
        ),
    ]
