# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stats', '0007_game_season'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playershotchartdetail',
            unique_together=set([('player', 'game', 'game_event_id')]),
        ),
    ]
