from django.conf.urls import url
from nba_fantasy import views, ajax_views, class_views

urlpatterns = [url(r'^$', class_views.IndexView.as_view(), name='index'),
               url(r'^login/$', views.login, name='login'),
               url(r'^create_league/$', class_views.FantasyLeagueFormView.as_view(),
                   name="create-league"),
               url(r'^league_homepage/(?P<league_id>[0-9]+)$', views.league_homepage,
                   name='league-homepage'),
               url(r'^edit_team/(?P<league_id>[0-9]+)$', views.create_team,
                   name='create-team'),
               url(r'^edit_team/(?P<league_id>[0-9]+)/(?P<team_id>[0-9]+)$', views.edit_team,
                   name='edit-team'),
               url(r'^view_team/(?P<team_id>[0-9]+)/$', views.view_team,
                   name='view-team'),
               url(r'^view_team/(?P<team_id>[0-9]+)/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/(?P<day>[0-9]{1,2})/$',
                   views.view_team, name='view-team-date'),
               url(r'^draft/(?P<league_id>[0-9]+)$', views.draft,
                   name='draft'),
               url(r'^free_agents/(?P<league_id>[0-9]+)$', views.free_agents,
                   name='free-agents'),
               url(r'^trade/(?P<league_id>[0-9]+)$', views.trade,
                   name='trade'),
               url(r'^accept_trade/(?P<transaction_id>[0-9]+)$', views.accept_trade,
                   name='accept-trade'),
               url(r'^schedule/(?P<league_id>[0-9]+)$', views.schedule,
                   name='schedule'),
               url(r'^matchup/(?P<matchup_id>[0-9]+)$', views.matchup,
                   name='matchup'),
               url(r'^standings/(?P<league_id>[0-9]+)$', views.standings,
                   name='standings'),
               url(r'^ajax/add_free_agent/$', views.add_free_agent, name='add-free-agent'),
               url(r'^ajax/propose_trade/$', views.propose_trade, name='propose-trade'),
               url(r'^ajax/update_fantasy_lineup', ajax_views.ajax_update_fantasy_lineup,
                   name='ajax-update-fantasy-lineup')
               ]
